name: Update Novel Chapters
on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: 

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install firebase-admin requests cloudscraper lxml python-dotenv

      - name: Create Secrets File
        run: |
          echo '${{ secrets.FIREBASE_CREDENTIALS }}' > serviceAccountKey.json

      - name: Run Scraper
        env:
          TARGET_USER_ID: ${{ secrets.TARGET_USER_ID }}
        run: python scraper.py
